site_name: My Notebook

theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to light mode

    font:
        text: Roboto
        code: Roboto Mono

    features:
        - navigation.tabs

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page Tree
nav:
    - Home: index.md
    - NN Quantization:
          - Table based Quantization: nn_quant/table_based_quant.md
          - Appendix: nn_quant/appendix.md
